# Generated by Django 5.2.13 on 2026-04-15 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.studyroom')),
            ],
        ),
    ]
